### ISSUE TITLE
unknown identifier STRING (TLC.tla:121:42)

### ISSUE THREAD

**Issue by pfeodrippe** [tlaplus/PlusPy#6]
I am using `EXTENDS` with the `TLC` module (e.g at the `HourClock` module) and it gives me the error

```
unknown identifier STRING (TLC.tla:121:42) 
```

**Comment by pfeodrippe** [comment]
Sorry, it was path related, I was using the `tmp` directory as the first path (very bad idea!) and there was a `TLC.tla` there.

o/

**Comment by amanshaikh75** [comment]
Hi Paulo - I am running into similar problem. Can you elaborate on how you fixed the problem?
